name: Deploy to Remote Server

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Установка Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Шаг 3: Установка зависимостей Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Шаг 4: Проверка работы скрипта Python
      - name: Test Python script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_TOKEN_TEST: ${{ secrets.TG_TOKEN_TEST }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SCHEMA: "public"
          SSH_HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
          SSH_USERNAME: ${{ secrets.DEPLOY_SERVER_USER }}
          SSH_PASSWORD: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          echo "Running Python script test..."
          
          echo "Starting Python script..."
          
          # Запустить с таймаутом (если скрипт работает постоянно)
          python main_test.py 2>&1

          echo "Python script test completed successfully"

      # Шаг 5: Сборка Docker-образа
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag pensonnelmanagerbot:latest

      # Шаг 6: Экспорт Docker-образа в tar-файл
      - name: Save Docker image as tar file
        run: docker save pensonnelmanagerbot:latest -o image_pmb.tar

      # Шаг 7: Изменение прав доступа к файлу
      - name: Set permissions on image_pmb.tar
        run: chmod 644 image_pmb.tar

      # Шаг 8: Передача tar-файла на сервер с помощью scp
      - name: Copy Docker image to server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: 22
          source: "image_pmb.tar"
          target: "~/deploy/"

      # Шаг 9: Загрузка образа и запуск контейнера на удалённом сервере
      - name: Load image and run container on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: 22
          script: |
            docker load -i ~/deploy/image_pmb.tar
            docker stop adminbot || true
            docker rm adminbot || true
            docker run -d --name adminbot \
              -e TG_TOKEN="${{ secrets.TG_TOKEN }}" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e SSH_HOST="${{ secrets.DEPLOY_SERVER_HOST }}" \
              -e SSH_USERNAME="${{ secrets.DEPLOY_SERVER_USER }}" \
              -e SSH_PASSWORD="${{ secrets.DEPLOY_SERVER_PASSWORD }}" \
              -e BASE_URL="${{ secrets.BASE_URL }}" \
              -e SCHEMA="public" \
              pensonnelmanagerbot:latest