name: Deploy to Remote Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Сборка Docker-образа
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag pensonnelmanagerbot:latest

      # Шаг 3: Экспорт Docker-образа в tar-файл
      - name: Save Docker image as tar file
        run: docker save pensonnelmanagerbot:latest -o image_pmb.tar

      # Шаг 4: Изменение прав доступа к файлу (для успешного копирования)
      - name: Set permissions on image_pmb.tar
        run: chmod 644 image_pmb.tar

      # Шаг 5: Передача tar-файла на сервер с помощью scp
      - name: Copy Docker image to server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: 22
          source: "image_pmb.tar"
          target: "~/deploy/"

      # Шаг 6: Загрузка образа и запуск контейнера на удалённом сервере по SSH
      - name: Load image and run container on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: 22
          script: |
            docker load -i ~/deploy/image_pmb.tar
            docker stop adminbot || true
            docker rm adminbot || true
            docker run -d --name adminbot \
              -e TG_TOKEN="${{ secrets.TG_TOKEN }}" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e SSH_HOST="${{ secrets.DEPLOY_SERVER_HOST }}" \
              -e SSH_USERNAME="${{ secrets.DEPLOY_SERVER_USER }}" \
              -e SSH_PASSWORD="${{ secrets.DEPLOY_SERVER_PASSWORD }}" \
              -e BASE_URL="${{ secrets.BASE_URL }}" \
              pensonnelmanagerbot:latest
